/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as BookHotelIdRouteImport } from './routes/book.$hotelId'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHotelIdRoute = BookHotelIdRouteImport.update({
  id: '/book/$hotelId',
  path: '/book/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HotelsRoute,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/$hotelId',
  path: '/$hotelId',
  getParentRoute: () => HotelsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/book/$hotelId': typeof BookHotelIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/book/$hotelId': typeof BookHotelIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels': typeof HotelsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/contact': typeof ContactRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRoute
  '/book/$hotelId': typeof BookHotelIdRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/contact'
    | '/hotels'
    | '/login'
    | '/owner'
    | '/book/$hotelId'
    | '/hotels/$hotelId'
    | '/hotels/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/contact'
    | '/login'
    | '/owner'
    | '/book/$hotelId'
    | '/hotels/$hotelId'
    | '/hotels'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/contact'
    | '/hotels'
    | '/login'
    | '/owner'
    | '/book/$hotelId'
    | '/hotels/$hotelId'
    | '/hotels/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  ContactRoute: typeof ContactRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  BookHotelIdRoute: typeof BookHotelIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$hotelId': {
      id: '/book/$hotelId'
      path: '/book/$hotelId'
      fullPath: '/book/$hotelId'
      preLoaderRoute: typeof BookHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HotelsRouteChildren {
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  ContactRoute: ContactRoute,
  HotelsRoute: HotelsRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  BookHotelIdRoute: BookHotelIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
